Module3 task1
htmlacademy-react/1870769-six-cities-16 pull request #3
Opened 2024-07-13 18:37 UTC by 1inokent

2024-07-14 04:14 UTC, Ekzaton requested changes

2024-07-14 04:14 UTC, Ekzaton commented on src/components/not-found-screen/NotFoundScreen .tsx
> +function NotFoundScreen(): JSX.Element {
[Б21.](https://up.htmlacademy.ru/react/16/criteries#b21) В названии файлов не используется разный регистр, а применяется разделение слов дефисом. Исключение составляют файлы, которые были созданы автоматически во время создания проекта.

2024-07-14 11:53 UTC, 1inokent commented on src/components/not-found-screen/NotFoundScreen .tsx
> +function NotFoundScreen(): JSX.Element {
поправил

2024-07-15 12:53 UTC, Ekzaton commented on src/components/not-found-screen/NotFoundScreen .tsx
> +function NotFoundScreen(): JSX.Element {
> поправил

Не вижу изменений. Компонент должен называться `not-found-screen.tsx` чтобы соответствовать критерию Б21

2024-07-15 13:40 UTC, merged